### ISSUE TITLE
Error in EJfunction: unused argument (buff_dist = 1)

### ISSUE THREAD

**Issue by jaxgoodlabs** [USEPA/EJSCREENBatch#27]
I'm running the Using_EJSCREENbatch Rmd file and encountering the following error:

Error in EJfunction(data_type = "landbased", LOI_data = rnd.pts, gis_option = "robust",  : unused argument (buff_dist = 1)

Is there a way to pull up documentation for EJfunction() to better understand what might be happening?

**Comment by arelkhattabi** [comment]
The input "buffer_dist" has been changed to simply "buffer"
