### ISSUE TITLE
Erro in EJfunction: object 'rnd.pts' not found

### ISSUE THREAD

**Issue by jaxgoodlabs** [USEPA/EJSCREENBatch#29]
Running the Using_EJSCREENbatch Rmd file, encountering the following error:

Error in EJfunction(data_type = "landbased", LOI_data = rnd.pts, gis_option = "robust",  : 
  object 'rnd.pts' not found

**Comment by adamtheising** [comment]
good catch -- corrected. thanks! -a

**Comment by adamtheising** [comment]
rename data object -> mpp
