### ISSUE TITLE
Error in EJfunction: object 'rnd.pts' not found

### ISSUE THREAD

**Issue by jaxgoodlabs** [USEPA/EJSCREENBatch#30]
The previous fix has not resolved this issue for me: 

Running the Using_EJSCREENbatch Rmd file, encountering the following error:

Error in EJfunction(data_type = "landbased", LOI_data = rnd.pts, gis_option = "robust", :
object 'rnd.pts' not found

**Comment by adamtheising** [comment]
The object _rnd.pts_ is from a previous version of the vignette. Please use the updated vignette, and set LOI_data = mpp.
