### ISSUE TITLE
SEDAC and ACS default data downloaded by the tool does not include data on Hawaii, Alaska, and Puerto Rico. 

### ISSUE THREAD

**Issue by ParkerJanMalek** [USEPA/EJSCREENBatch#31]
The fetch_acs_data.R function explicitly excludes Alaska and Hawaii in the ACS data pull.  

## State lists
    state.list <- c(state.abb, 'DC')
    state.list <- state.list[!(state.list %in% c('AK', 'HI'))]

Is there a plan to incorporate this data into the tool (including Puerto Rico), or is this something that needs to be included manually?

**Comment by adamtheising** [comment]
While inclusion of these states/territories would be nice, we have no immediate plans to incorporate AK ,HI, PR into tool due to (1) SEDAC's raster spanning only cont'l US and (2) added complexity with projections when including AK, HI in a nat'l analysis.
