### ISSUE TITLE
Facility state duplication issue causing population overestimates and throwing errors

### ISSUE THREAD

**Issue by ParkerJanMalek** [USEPA/EJSCREENBatch#32]
[NY_PWS_Boundaries.zip](https://github.com/USEPA/EJSCREENBatch/files/8157409/NY_PWS_Boundaries.zip)

The robust methodology in the EJScreenBatch R tool has issues with certain polygon inputs.  

The facility_buff variable created for three New York Polygons (PWSID: NY5903456, NY5903435, NY7003493, polygons attached to this issue), produces duplicate records because it thinks these system areas are in multiple states. From the EJfunction.R script: 

# Extract the state associated with each facility 
### Areal apportionment using circular buffers around facilities 
          state.shapes <- spData::us_states %>% st_as_sf() %>% 
          st_transform(crs=102005) %>% 
          dplyr::select('NAME') %>% 
          rename(facility_state = NAME) 
          facility_buff <- st_join(LOI_data, state.shapes, join=st_intersects) %>% 
          st_buffer(dist = units::set_units(i,"mi")) 

The spatial join above that creates the facility_buff variable produces multiple state entries for these polygons even though a buffer of 0 is defined in the function (see below)

# EJfunction call used
          my.EJ.data.robust <- EJfunction(data_type = "landbased",
                     LOI_data = system_polygons, 
                     gis_option = "robust", 
                     buffer = 0
                     raster_data = raster.path)

NOTE: NY5903435 and NY7003493 runs through the tool without error, but they produce over-estimates of population because of the duplication. NY5903456 ends up producing a mutate error in the areal_apportionment.R script.

**Comment by adamtheising** [comment]
Best I can tell, a few things going on here:

1. tigris::states() is likely preferable to spData::us_states(), and we will push an update with this modification asap. Maybe it's a resolution thing, or maybe a data vintage thing, but in any case, after this switch, NY7003493 and NY5903435 both fall entirely within NY state boundaries.
2.  Using the tigris hi-res shapefile, a quick test shows that NY5903456 still intersects with both NY and CT. So as drawn currently, this polygon does indeed seem to span two states -- I find it hard to take error with the Census shapefiles.
```
ny.pws <- sf::st_read('NY_PWS_Boundaries.shp') %>%
  sf::st_transform(crs=4326)
state.shapes <- tigris::states() %>% sf::st_as_sf() %>%
  sf::st_transform(crs = 4326)
state.intersect <- sf::st_intersection(ny.pws,state.shapes2)
```
3.  When a polygon falls in two states the function does crash. We hadn't put in place anything for allocating polygons to a single state (this only matters for calculations of state percentiles in the areal_apportionment function), but are now adding a  simple rule that polygons are attributed to the state where the majority of the polygon lies. 

So in all, these changes will look something like:

```
state.shapes <- tigris::states() %>% st_as_sf() %>%
  st_transform(crs="ESRI:102005") %>%
  dplyr::select('NAME') %>%
  rename(facility_state = NAME)
facility_buff <- st_join(facility_buff, state.shapes, join=st_intersects, largest = T)
```

Many thanks for raising this issue -- we hadn't put as much close thought into polygon scenarios, and these PWS boundaries are proving a great test case.
