### ISSUE TITLE
Error with # 5 example in Adjusting User Selected Options

### ISSUE THREAD

**Issue by jaxgoodlabs** [USEPA/EJSCREENBatch#33]
In the updated vignette, the # 5 example in the Adjusting User Selected Options section generates the following error:

Error in EJfunction(data_type = "landbased", LOI_data = mpp, input_name = name,  : 
  object 'name' not found

Instructions read: "the *input_name* should be set equal to the name of the sf object's location name column," but in example, input name is set equal to "name," which doesn't exist in the LOI_data (mpp object). What variable name should we replace it with?

**Comment by adamtheising** [comment]
Vignette updated with dataset-appropriate variable name.
