### ISSUE TITLE
Coordinate References aren't working on certain systems

### ISSUE THREAD

**Issue by ParkerJanMalek** [USEPA/EJSCREENBatch#34]
The coordinate references as defined by the string below in **EJFunction.R**, **areal_apportionment.R**, and **fetch_data_ej.R** results in a missing crs error:

**"ESRI:102005"**

_Error in CPL_transform(x, crs, aoi, pipeline, reverse, desired_accuracy,  : 
  crs not found: is it missing?_

```
LOI_data <- LOI_data %>%
      tibble::rowid_to_column("shape_ID") %>%
      st_transform("ESRI:102005")
```
Replacing the string with the ESRI projection number fixes the issue

```
LOI_data <- LOI_data %>%
      tibble::rowid_to_column("shape_ID") %>%
      st_transform(102005)
```

Additionally, the raster projection in the areal_apportionment.R function throws a slightly different error

_Error in CRS(SRS_string = x) : no arguments in initialization list_

**Line 24-25 in areal_apportionment.R:**

```
raster_extract <- raster::raster(layers) %>%
    raster::projectRaster(crs="ESRI:102005")
```
Simply replacing the string with the numeric code does not work and the same error is thrown. Instead, manually applying the associated proj4 projection string for the USA Contiguous Equidistant Conic projection (http://epsg.io/102005) resolves the error:

```
raster_extract <- raster::raster(layers) %>%
    raster::projectRaster(crs="+proj=eqdc +lat_0=39 +lon_0=-96 +lat_1=33 +lat_2=45 +x_0=0 +y_0=0 +datum=NAD83 +units=m +no_defs")
```
Below are versions of the geospatial packages being used here:

**rgeos_0.5-5** 
**sp_1.4-5**    
**sf_0.9-8**    
**rgdal_1.5-23**

**Comment by adamtheising** [comment]
Addressed in version 2.0.1 update.
