### ISSUE TITLE
No option for 2023 data generates error

### ISSUE THREAD

**Issue by crw41** [USEPA/EJSCREENBatch#38]
Running **EJfunction( )** without already downloading the EJSCREEN files results in an error:
```
landdata <- EJfunction(data_type = "landbased",
                       LOI_data = sb,
                       gis_option = "fast", 
                       buffer = 0.01,
                       raster_data = raster_path)
```
_Error in zipunzippednames(yr) : object 'zipname' not found_

The traceback shows:
![image](https://github.com/USEPA/EJSCREENBatch/assets/75647150/2462c56a-03be-4e8b-9d7b-9af5c7c83936)

Setting `yr <- 2022` before calling `EJfunction( )` does not resolve the error. 

I think the error is being generated by line 86 of **ejscreen.download.gdb.R**, within the EJSCREEN data download function `ejscreen.download.local( )`. The 2023 version of EJSCREEN is available [here](https://gaftp.epa.gov/EJSCREEN/2023/), but there is no option for `yr==2023` within the `zipunzippednames(yr)` function, which is defined in lines 59-85 of **ejscreen.download.gdb.R**. This results in `return(c(zipname, unzippedname))` generating an error because `zipname` and `unzippedname` are not defined if `yr==2023`. 

I think simply adding another statement (`if(yr == 2023)`) within `zipunzippednames(yr)` that correctly defines `zipname` and `unzippedname` would fix the issue. Note that the file names for the 2023 EJSCREEN files are slightly different than the 2022 files. 

Please let me know if more documentation or follow up is needed!

**Comment by adamtheising** [comment]
Address in version 2.0.1 update. Thanks for flagging!
